### PR TITLE
Added scheduled backups to admin page

### PR DESCRIPTION
**Pull request by JRogaishio**
- Added the ability to enable backups with a set frequency (every x hours)
- Added the ability for backups to be rolling or auto-delete if they are x hours old
- Fixed admin.php page $user variable so faces now appear
- Re-added userProfile.php but removed the ability to update any items. (Before it was just a broken link)
  
Let me know if this is worth bringing into the main repo. Also if I need to make any tweaks / code style changes. I'm currently running this on my own server and the backups appear to be running properly via cron.

### CODE REVIEW

**Comment by Alanaktion** [comment]
This is awesome! I'll take a look at it and if it all looks good, I'll merge it.

**Comment by Alanaktion** [comment]
This looks good, I'll probably remove the user profile page again and just add it's functionality to the dashboard, but this works for now.

**Comment by JRogaishio** [comment]
Thanks! Also in the future I'll be sure to leave out all those tabs in my newlines.
My IDE likes to add those for some reason.

**Comment by Alanaktion** [comment]
I don't mind the whitespace, I just have my editor set to remove trailing whitespace from lines and add a newline at the end of all files, since the extra whitespace is unnecessary. The code isn't consistent enough in this repo for me to care about little things like that :)

**Pull request merged**
